### ISSUE TITLE
Wrong column name

### ISSUE THREAD

**Issue by cpavloud** [emo-bon/observatory-aaot-crate#3]
Column arr_hq_date should be arr_date_hq in https://github.com/emo-bon/observatory-aaot-crate/blob/main/logsheets/transformed/water_sampling.csv

@melinalou

**Comment by melinalou** [comment]
don't have the permission to change headers

**Comment by cpavloud** [comment]
@melanthia can you?

**Comment by cpavloud** [comment]
Done
