### ISSUE TITLE
Wrong column name

### ISSUE THREAD

**Issue by cpavloud** [emo-bon/observatory-aaot-crate#4]
ENA_accesion_number_umbrella and ENA_accesion_number_project should be ENA_accession_number_umbrella and ENA_accession_number_project in https://github.com/emo-bon/observatory-aaot-crate/blob/main/logsheets/transformed/water_observatory.csv

@melinalou

**Comment by melinalou** [comment]
don't have permission to change headers

**Comment by cpavloud** [comment]
@melanthia can you?

**Comment by cpavloud** [comment]
Done
